common:
 work_dir: 'workspace'
 result_dir: 'result'
 verbose: False
 log_size: 2097152
 packages_metadata_repo_url: "https://github.com/open-power-host-os/versions.git"
 packages_metadata_repo_branch: 'master'
 packages_metadata_repo_refspecs:
   - '+refs/heads/*:refs/remotes/origin/*'
   - '+refs/pull/*:refs/remotes/origin/pr/*'
 http_proxy: ''
 distro_name: 'CentOS'
 distro_version: '7'
 architecture: 'ppc64le'
 mock_binary: "/usr/bin/mock"
 pungi_binary: "/usr/bin/pungi"
 commit_updates: True
 push_updates: True
 updater_name: ''
 updater_email: ''
build_packages:
 packages: []
 keep_build_dir: False
 force_rebuild: False
 mock_args:
   # If the system has less RAM than required, the plugin will be disabled
   "--enable-plugin=tmpfs
   --plugin-option=tmpfs:keep_mounted=True
   --plugin-option=tmpfs:max_fs_size=32g
   --plugin-option=tmpfs:required_ram_mb=39800
   --verbose"
 update_packages_repos_before_build: True
build_release_notes:
 release_notes_repo_url: "https://github.com/open-power-host-os/open-power-host-os.github.io.git"
 release_notes_repo_branch: "master"
 push_repo_url: ''
 push_repo_branch: "master"
build_iso:
    iso_name: "OpenPOWER-Host_OS"
    mock_args:
      # If the system has less RAM than required, the plugin will be disabled
      "--enable-plugin=tmpfs
      --plugin-option=tmpfs:keep_mounted=True
      --plugin-option=tmpfs:max_fs_size=32g
      --plugin-option=tmpfs:required_ram_mb=39800
      --verbose"
    pungi_args: "--isfinal --nosource --nodebuginfo"
    packages_dir: "result/packages/latest"
    automated_install_file: "host-os.ks"
    installable_environments:
        OpenPOWER Host OS all:
            - "open-power-host-os-all"
        OpenPOWER Host OS base:
            - "open-power-host-os-base"
        OpenPOWER Host OS container:
            - "open-power-host-os-container"
        OpenPOWER Host OS virtualization:
            - "open-power-host-os-virt"
        OpenPOWER Host OS virtualization management:
            - "open-power-host-os-virt-management"
        OpenPOWER Host OS RAS:
            - "open-power-host-os-ras"
    iso_repo_packages_groups:
        - "OpenPOWER Host OS all"
        - "OpenPOWER Host OS base"
        - "OpenPOWER Host OS container"
        - "OpenPOWER Host OS virtualization"
        - "OpenPOWER Host OS virtualization management"
        - "OpenPOWER Host OS RAS"
    iso_repo_packages: []
    mock_iso_repo_name: "host_os"
    mock_iso_repo_dir: "/host-os-repo"
    distro_repos_urls:
        base: "http://mirror.centos.org/altarch/7/os/ppc64le/"
        updates: "http://mirror.centos.org/altarch/7/updates/ppc64le/"
        extras: "http://mirror.centos.org/altarch/7/extras/ppc64le/"
        epel: "http://download.fedoraproject.org/pub/epel/7/ppc64le/"
update_metapackage:
 push_repo_url: ''
 push_repo_branch: "master"
update_versions:
 packages: []
 push_repo_url: ''
 push_repo_branch: "master"
update_versions_readme:
 push_repo_url: ''
 push_repo_branch: "master"
